### ISSUE TITLE
glmm.gei interaction function: subscript out of bounds

### ISSUE THREAD

**Issue by ConnieXuhm** [large-scale-gxe-methods/MAGEE#1]
Hi @xwang21 @hanchenphd ,
I followed your suggestions using MAGEE for longitudinal study. However, both my data and the example data meet an error.
Here I use example data (pheno2) as an example.
```
library(GMMAT)
library(MAGEE)
data(example)
attach(example)
model0<-glmmkin(y.trend~sex+time,data=pheno2,id="id",kins="GRM", family=gaussian(link="identity"))   #it runs normal
infile<-system.file("extdata","geno.gds","package="MAGEE")
gds_outfile<-tempfile()
glmm.gei(model0,interaction='sex',geno.file=infile,outfile=gds_outfile)
```
Here is the error:
Error in as(x,"matrix")[i,,drop=drop]:subscript out of bounds

I tried those solutions:
1) In pheno file without longitudinal format, glmm.gei works.
2) In pheno2 file using GMMAT::glmm.score, it works for longitudinal format.
3) change interaction variable as "time", or change the family module to" inverse“, etc, which were no change of the error.
Could you help me with this?
Thanks again!

**Comment by xwang21** [comment]
Thank you for bringing this to our attention. We found a bug in our code with longitudinal data. We are working on it and will fix it in the next version.
