### ISSUE TITLE
How to determine N for variant source?

### ISSUE THREAD

**Issue by jsdron** [large-scale-gxe-methods/MAGEE#20]
In using glmm.gei.meta(), the output provides N_samples. What I am also looking for is a column to indicate how many summary stat files this variant was contained in ("N_source"). For example, if I used summary stat files from Cohort_A, Cohort_B, and Cohort_C, I would want to know if each variant in the meta-analyzed output was present in 1, 2, or 3 of these cohorts. For quality purposes, I would be inclined to exclude variants that only appear in 1 cohort.

Is it possible to have this feature added? Alternatively, is there a way to identify these "1-source" variants in the meta-analyzed output some other way? 

Thank you for your time and consideration!

**Comment by hanchenphd** [comment]
Thank you for your comment! I think this could be better performed using your meta-analysis input files (as a QC step) rather than the meta-analysis output. You could pre-filter variants that only appear in one study.

Best,
Han

**Comment by jsdron** [comment]
Thank you, @hanchenphd, for your quick reply! We'll build it into our pipeline then. 

So does that mean if a variant is only present in 1 summary stat file and it gets passed in for the meta-analysis, it will still be included in the final output?

Thanks again!

**Comment by jsdron** [comment]
Thanks!
