### ISSUE TITLE
Missing betas and p-values

### ISSUE THREAD

**Issue by jsdron** [large-scale-gxe-methods/MAGEE#21]
A quick clarification question: if we run MAGEE and in our output file, the beta and p-value columns are all listed as NaN, does that mean the model failed? (Noting the sample sizes used for these particular analyses were <400 samples) I'm wondering if it is a possible sample size issue, or if there might be another error I should look into.

Thanks!

**Comment by hanchenphd** [comment]
Most likely your residual variance estimate converged to 0 in the null model fitting. You can verify that by turning on `verbose = TRUE` in the null model fitting.

Best,
Han

**Comment by jsdron** [comment]
Thank you, I'll give that a try!
